### PR TITLE
Update material_import.py, Texture Alpha node to Principled BSDF Alpha

### PR DESCRIPTION
**Pull request by rizzntine**
added change to create_vertex_material so that we can connect the Texture Alpha node to Principled BSDF Alpha node

### CODE REVIEW

**Comment by Tarcontar** [comment]
Hi, thanks for your contribution!
This results for the file i tested in this configuration:
image
I dont think this is the desired behaviour.
Could you please show how this looks for the file you tested?

**Comment by rizzntine** [comment]
Hi! Thanks for the test!
Functionally, the behaviour is functioning as intended - or it would be, i just noticed that the second image is connecting the color node to the alpha - that is definitely not the intent. It should connect Alpha to Alpha.
Untitled
Most of my testing scope was focused on C&C Generals Faction Buildings which used transparent materials, eg. The USA Airfield (ABARFRCCMD.w3d), China's War Factory (NBWARFACT.w3d)...

I'm afraid I have limited time to look into this but I'll attempt to take a deeper dive into this and resolve the microscopic issues before they turn macro. What was your tested configuration in question?

**Comment by Michaelschnabel-DM** [comment]
@rizzntine  Hi, i tried to properly link the texture:
image

Could you please check if this still results in the correct behaviour? I actually do not really have a lot of generals models lying around.

**Comment by rizzntine** [comment]
Hi! Yes, it links fine now, splendid! 
ApplicationFrameHost_ANLbrco5Db
The current patch fork however does not have the multiple material rework that has been done on the fork since, so it looks like this. I've went ahead and implemented the node tree manipulation into the master branch of the fork with, here is how the result looks now:
ApplicationFrameHost_YmRxOsdFoo
Therefore, I will be closing this pull request in favor of moving to the more functional one.

**Pull request closed without merging**
