### PR TITLE
Support W3D_CHUNK_VERTICES_2 and W3D_CHUNK_NORMALS_2

### PR DESCRIPTION
**Pull request by nkx111**
Write the second group of vertices/normals which translate according to the extra bone group.

This PR also scales up bone weight if not add up to 100%.

### CODE REVIEW

**Comment by Tarcontar** [comment]
@nkx111 Hi, thank you for updating the branch. There are a few tests that fail with your changes. Could you please have a look at them and try to fix them?

**Comment by nkx111** [comment]
Hi @Tarcontar, I updated the tests and hopefully they are fixed. There are three items which are changed:

* **test_node_order**: when exporting "skin" meshes, the chunks W3D_CHUNK_VERTICES_2 and W3D_CHUNK_NORMALS_2 are written, therefore we shall expect two 'Vertices' and 'Normals'.
*  **test_write_read_variant2**: new size is expected due the the additional vertices and normals.
* **test_retrieve_meshes_with_bone_weights_not_adding_up_to_100_percent**: bone weight normalization is introduced and the output message is updated.

**Comment by nkx111** [comment]
I don't know why the updated size calculation with the second vertics group leads to failure in test_roundtrip. I reverted those commits. Now it still uses the old mesh-size calculation, but won't write the second vertics group in the test. The tests are successful on my local computer.

**Comment by Tarcontar** [comment]
Hi, we definetely need the second vertices group in the size calculation. Please readd this otherwise the created mesh files will be incorrect. If you cant get the test_roundtrip to work i will have a look then.

**Comment by nkx111** [comment]
Hi @Tarcontar, I think the size issue has been fixed.

**Review by Michaelschnabel-DM — APPROVED** [review]
This looks fine to me know. Thank you very much @nkx111 !

**Pull request merged**
