### PR TITLE
w3d properties internal rename, multiple material per mesh object support, alpha transparency support, empty data object error fix

### PR DESCRIPTION
**Pull request by rizzntine**
Renamed from blend_mode to blend_method in accordance with blender internals

### CODE REVIEW

**Comment by rizzntine** [comment]
> blender_namFE5Ga7j In the W3D Properties panel, the blend mode showed an enum number rather than what it actually represented, and changing this slider value would result in nothing actually happening. blender_kKhYh9KVFs I renamed the blend_mode properties to blend_method, so that it would accurately reflected blender's internal method. This results in the enum displaying as a menu, and changing this also changes the blend mode of the selected material.

**Comment by Tarcontar** [comment]
Could you please reupload the images attached?

**Comment by rizzntine** [comment]
Ah, apologies, keep forgetting that with every change the images cdn link also changes. 
285604113-f5152ff3-e301-4f9e-b94b-1f84f03d8e6f
This is before
285604204-9719fc3a-2633-4b09-9454-ff8c5b2255b6
This is after, and just in-case that these images also fail, i am attaching an imgur image link as well. [https://imgur.com/a/CDQ643T](url)

**Comment by Tarcontar** [comment]
Hi @rizzntine, thank you for your contribution!
Could you please update this branch? We fixed CI for 4.0 now

**Comment by Tarcontar** [comment]
@rizzntine would it be possible for you to have a look at the failing tests?

**Comment by rizzntine** [comment]
Should be good to go now.

**Pull request merged**
